package flp.example;

import flp.jsonSimple.Context;
import flp.jsonSimple.JsonObject;

public class Person implements SerializableJsonObject {

	private String vorname;
	private String nachname;
	private int alter;
	
	

	public Person(String vorname, String nachname, int alter) {
		setVorname(vorname);
		setNachname(nachname);
		setAlter(alter);
	}
	public Person() {
		this("empty","empty",0);
	}
	public Person newInstance(String json) {
		JsonObject expression = new JsonObject();
		expression.interprete(new Context(json));
		String vorname = (String) expression.get("vorname");
		String nachname = (String) expression.get("nachname");
		int alter = (Integer) expression.get("alter");
		return new Person(vorname, nachname, alter);
	}
	
	public String getVorname() {
		return vorname;
	}
	public void setVorname(String vorname) {
		this.vorname = vorname;
	}
	public String getNachname() {
		return nachname;
	}
	public void setNachname(String nachname) {
		this.nachname = nachname;
	}
	public int getAlter() {
		return alter;
	}
	public void setAlter(int alter) {
		if(alter < 0){
			throw new RuntimeException("Alter kleiner 0");
		}
		this.alter = alter;
	}
	
	public String toJson(){
		return "{\n\t\"vorname\" : \""+vorname+"\",\n\t\"nachname\" : \""+nachname+"\",\n\t\"alter\" : "+alter+"\n}";
	}
	
//	//autogenerated: DO NOT CHANGE!
//	@Override
//	public int hashCode() {
//		final int prime = 31;
//		int result = 1;
//		result = prime * result + alter;
//		result = prime * result + ((nachname == null) ? 0 : nachname.hashCode());
//		result = prime * result + ((vorname == null) ? 0 : vorname.hashCode());
//		return result;
//	}
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj)
//			return true;
//		if (obj == null)
//			return false;
//		if (getClass() != obj.getClass())
//			return false;
//		Person other = (Person) obj;
//		if (alter != other.alter)
//			return false;
//		if (nachname == null) {
//			if (other.nachname != null)
//				return false;
//		} else if (!nachname.equals(other.nachname))
//			return false;
//		if (vorname == null) {
//			if (other.vorname != null)
//				return false;
//		} else if (!vorname.equals(other.vorname))
//			return false;
//		return true;
//	}
	
}
